session "Goblint_Formalization" in "src" = "HOL-IMP" +
  description "Isabelle/HOL formalization of the Goblint static analysis pipeline"
  sessions
    TD
    "Dijkstra_Shortest_Path"
  directories
    "IMP2"
    "CFG"
    "CFG/Collecting"
    "Domains"
    "Equations"
    "Solver"
    "Pipeline"
    "Examples"
  theories
    Goblint_Formalization
    IMP2_Globals
    IMP2_Proc
    CFG_Trace_Collect
    Trace_Soundness
    TD_CFG_Core
    TD_Widen_Interface
    TD_WN_Interface
    Example_Sign_Analysis
    Example_Interval_Analysis
    Example_Interval_Widen
    Example_CFG_Collecting_Equiv
    Example_GraphViz
    Example_NonTerminating_Safe
    Example_Trace_NonTerminating
