(rule
 (targets Voblint_CLI.ml)
 (deps ../codegen/generated/ml/Voblint_CLI.ml)
 (action (copy %{deps} %{targets})))

(menhir
 (modules vimp_parser)
 (flags --unused-precedence-levels))

(ocamllex vimp_lexer)

(library
 (name voblint_frontend)
 (wrapped false)
 (modules
  Voblint_CLI
  vimp_positions
  vimp_parser
  vimp_lexer
  vimp_frontend)
 (libraries str zarith)
 (flags (:standard -w -8-11-20-27-32-37-39 -warn-error -A)))

(library
 (name voblint_rendering)
 (wrapped false)
 (modules dot_render)
 (libraries voblint_frontend)
 (flags (:standard -w -8-11-20-27-32-37-39 -warn-error -A)))

(executable
 (name main)
 (modules
  html_report
  main)
 (libraries voblint_frontend voblint_rendering str zarith unix)
 (flags (:standard -w -8-11-20-27-32-37-39 -warn-error -A)))

(executable
 (name browser_main)
 (modules browser_main)
 (modes js)
 (libraries
  voblint_frontend
  voblint_rendering
  js_of_ocaml
  zarith
  zarith_stubs_js)
 (flags (:standard -w -8-11-20-27-32-37-39 -warn-error -A)))
