(* GENERATED by scripts/gen_vimp_menhir.py from grammar/vimp.yaml. Do not hand-edit; regenerate instead. *)
{
open Vimp_parser

exception Lex_error of { line : int; col : int; msg : string }

let error lexbuf msg =
  let pos = Lexing.lexeme_start_p lexbuf in
  raise (Lex_error { line = pos.Lexing.pos_lnum; col = pos.Lexing.pos_cnum - pos.Lexing.pos_bol + 1; msg })
}

let digit = ['0'-'9']
let ident_start = ['a'-'z' 'A'-'Z' '_']
let ident_char = ident_start | digit

rule token = parse
  | [' ' '\t' '\r']  { token lexbuf }
  | '\n'              { Lexing.new_line lexbuf; token lexbuf }
  | "//" [^ '\n']*    { token lexbuf }
  | "global"            { GLOBAL }
  | "void"              { VOID }
  | "skip"              { SKIP }
  | "return"            { RETURN }
  | "__voblint_check"   { CHECK }
  | "if"                { IF }
  | "else"              { ELSE }
  | "while"             { WHILE }
  | "true"              { BOOL_TRUE }
  | "false"             { BOOL_FALSE }
  | "int8"              { TINT8 }
  | "uint8"             { TUINT8 }
  | "int16"             { TINT16 }
  | "uint16"            { TUINT16 }
  | "int32"             { TINT32 }
  | "uint32"            { TUINT32 }
  | "int64"             { TINT64 }
  | "uint64"            { TUINT64 }
  | ":="                { ASSIGN }
  | "+"                 { PLUS }
  | "-"                 { MINUS }
  | "*"                 { STAR }
  | "<"                 { LT }
  | "=="                { EQEQ }
  | "&&"                { AND }
  | "||"                { OR }
  | "!"                 { NOT }
  | "{"                 { LBRACE }
  | "}"                 { RBRACE }
  | "("                 { LPAREN }
  | ")"                 { RPAREN }
  | ";"                 { SEMI }
  | ","                 { COMMA }
  | ident_start ident_char* as s  { IDENT s }
  | digit+ as s                   { INT (int_of_string s) }
  | eof                           { EOF }
  | _ as c  { error lexbuf (Printf.sprintf "unexpected character %C" c) }
