#!/usr/bin/env python3
"""Generate a Typst dictionary mapping Isabelle ASCII symbol names to Unicode.

Theory sources are ASCII-only by project rule, so a snippet pasted into the
thesis arrives as ``\\<Longrightarrow>`` rather than as the glyph a reader
expects. This turns Isabelle's own symbol table into a lookup the Typst
library uses to decode snippets at render time -- the same table Isabelle
itself uses, so the two can never disagree.

Usage:
    python3 thesis/tools/gen_isabelle_symbols.py [ISABELLE_HOME] > out.typ
"""
import re
import subprocess
import sys
from pathlib import Path


def isabelle_home() -> Path:
    if len(sys.argv) > 1:
        return Path(sys.argv[1])
    out = subprocess.run(
        ["isabelle", "getenv", "-b", "ISABELLE_HOME"],
        capture_output=True, text=True, check=True)
    return Path(out.stdout.strip())


def main() -> None:
    table = isabelle_home() / "etc" / "symbols"
    entries = []
    for line in table.read_text(encoding="utf-8").splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        name, _, rest = line.partition(" ")
        m = re.search(r"code:\s*0x([0-9a-fA-F]+)", rest)
        if not m:
            continue
        entries.append((name, chr(int(m.group(1), 16))))

    print("// Generated by thesis/tools/gen_isabelle_symbols.py -- do not edit.")
    print(f"// {len(entries)} symbols from Isabelle's etc/symbols.")
    print("#let isabelle-symbols = (")
    for name, glyph in entries:
        key = name.removeprefix("\\<").removesuffix(">")
        if not re.fullmatch(r"[A-Za-z0-9^_]+", key):
            continue
        print(f'  "{key}": "{glyph}",')
    print(")")


if __name__ == "__main__":
    main()
