#!/usr/bin/env python3
"""Carry the README's playground figures into the thesis, with their runs.

Each README figure is a screenshot of the browser playground on a program from
``docs/readme-figures``, regenerated by ``scripts/capture_readme_figures.mjs``
rather than edited. The thesis shows the same figures, so it must read them from
the same place -- but Typst reads only below its root, and a figure whose link
was typed by hand can quietly stop matching the program it shows.

This tool reads ``thesis/shared/playground-figures.toml`` and, for each figure,
copies the image and the program under ``thesis/shared/generated/playground/``
and writes ``playground.json`` with the link that opens that program at those
settings, built by the same encoder the README and the playground's Share
button use. ``--check`` fails when a copy or a link no longer matches the
sources, naming the figure.

    python3 thesis/tools/playground_figures.py            # write
    python3 thesis/tools/playground_figures.py --check    # fail on drift
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import tomllib

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "scripts"))

import playground_link  # noqa: E402

MANIFEST = REPO / "thesis" / "shared" / "playground-figures.toml"
OUT_DIR = REPO / "thesis" / "shared" / "generated" / "playground"
INDEX = OUT_DIR / "playground.json"


def build() -> tuple[dict[str, dict[str, str]], dict[Path, bytes]]:
    """The index and the files it refers to, from the manifest and the sources."""
    manifest = tomllib.load(MANIFEST.open("rb"))
    index: dict[str, dict[str, str]] = {}
    files: dict[Path, bytes] = {}
    for name, entry in manifest["figures"].items():
        image = REPO / entry["image"]
        if not image.is_file():
            sys.exit(f"playground_figures: {name}: no such image {entry['image']}")
        files[OUT_DIR / f"{name}.png"] = image.read_bytes()
        record = {
            "image": f"{name}.png",
            "analysis": entry["analysis"],
            "globals": entry.get("globals", "warrow"),
            "context": entry.get("context", "none"),
            "why": entry["why"],
        }
        if "k" in entry:
            record["k"] = str(entry["k"])
        if "program" in entry:
            program = REPO / entry["program"]
            if not program.is_file():
                sys.exit(
                    f"playground_figures: {name}: no such program {entry['program']}"
                )
            source = program.read_text()
            files[OUT_DIR / f"{name}.vimp"] = source.encode()
            record["program"] = f"{name}.vimp"
            record["url"] = playground_link.link(
                source,
                entry["analysis"],
                entry.get("globals", "warrow"),
                entry.get("context", "none"),
                entry.get("k"),
            )
        else:
            # A run of a bundled example: the settings alone open it.
            record["url"] = playground_link.link(
                "",
                entry["analysis"],
                entry.get("globals", "warrow"),
                entry.get("context", "none"),
                entry.get("k"),
            ).split("#code=")[0]
        index[name] = record
    files[INDEX] = (json.dumps(index, indent=2, sort_keys=True) + "\n").encode()
    return index, files


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail on any drift")
    args = ap.parse_args()

    index, files = build()
    if args.check:
        stale = [
            p.relative_to(REPO).as_posix()
            for p, data in files.items()
            if not p.is_file() or p.read_bytes() != data
        ]
        extra = sorted(
            p.relative_to(REPO).as_posix() for p in OUT_DIR.glob("*") if p not in files
        )
        if stale or extra:
            for p in stale:
                print(f"playground_figures: stale: {p}", file=sys.stderr)
            for p in extra:
                print(f"playground_figures: unlisted: {p}", file=sys.stderr)
            print(
                "playground_figures: run `pixi run thesis-playground-write`",
                file=sys.stderr,
            )
            return 1
        print(f"playground_figures: {len(index)} figure(s) match their sources")
        return 0

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for p in OUT_DIR.glob("*"):
        if p not in files:
            p.unlink()
    for p, data in files.items():
        p.write_bytes(data)
    print(
        f"playground_figures: wrote {len(index)} figure(s) to {OUT_DIR.relative_to(REPO)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
