#!/usr/bin/env python3
"""Generates the VIMP frontend -- a Menhir parser (vimp_parser.mly) and a
real ocamllex lexer (vimp_lexer.mll) -- from the canonical grammar/vimp.yaml.

This is the source of cli/vimp_parser.mly and cli/vimp_lexer.mll (M5 of the
grammar-unification investigation: the production CLI cutover). The
generated .mly/.mll are committed, the same convention codegen/generated/
already uses for Isabelle-generated sources: `pixi run cli-build`
(scripts/mk/cli-build.sh) needs only menhir/ocamllex/ocamlfind, not Python,
extending its "does not require Isabelle" framing to "does not require
regenerating the frontend either, unless grammar/vimp.yaml changed."

Requires PyYAML to regenerate (`pip install pyyaml`, or `pixi install` from
the repo root already has it) -- not to build.

Usage: python3 scripts/gen_vimp_menhir.py [grammar/vimp.yaml] [out_dir]
"""

import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_GRAMMAR = REPO_ROOT / "grammar" / "vimp.yaml"
DEFAULT_OUT = REPO_ROOT / "cli"

HEADER = (
    "(* GENERATED by scripts/gen_vimp_menhir.py from grammar/vimp.yaml. "
    "Do not hand-edit; regenerate instead. *)\n"
)

# -- `special: name` productions, keyed by that name (not by production
# name -- grammar/vimp.yaml's header comment explains what each covers). ---
SPECIAL_ACTIONS = {
    "integer_literal": "Voblint_CLI.Core.N (Voblint_CLI.Core.Int_of_integer (Z.of_int v0))",
    "unary_minus": """\
match v1 with
      | Voblint_CLI.Core.N (Voblint_CLI.Core.Int_of_integer z) ->
        Voblint_CLI.Core.N (Voblint_CLI.Core.Int_of_integer (Z.neg z))
      | _ ->
        Voblint_CLI.Core.Minus
          (Voblint_CLI.Core.N (Voblint_CLI.Core.Int_of_integer Z.zero), v1)""",
}


# -- `lower: {ctor: ..., args: [...]}` / `lower: {tuple: [...]}` renderer --

def render_lower_arg(arg: dict) -> str:
    if "rhs" in arg:
        return f"v{arg['rhs']}"
    if "some" in arg:
        return f"(Some {render_lower_arg(arg['some'])})"
    if "none" in arg:
        return "None"
    if "literal" in arg:
        return "true" if arg["literal"] else "false"
    raise ValueError(f"unrecognized lower arg shape: {arg}")


def render_lower(lower: dict) -> str:
    if "tuple" in lower:
        return "(" + ", ".join(f"v{i}" for i in lower["tuple"]) + ")"
    ctor = f"Voblint_CLI.Core.{lower['ctor']}"
    args = [render_lower_arg(a) for a in lower.get("args", [])]
    if not args:
        return ctor
    if len(args) == 1:
        return f"{ctor} {args[0]}"
    return f"{ctor} (" + ", ".join(args) + ")"


def render_action(prod: dict) -> str:
    """Renders exactly one of a production's three possible AST-construction
    shapes -- see grammar/vimp.yaml's header comment for what each covers."""
    special = prod.get("special")
    if special:
        return SPECIAL_ACTIONS[special]
    if "passthrough" in prod:
        return f"v{prod['passthrough']}"
    return render_lower(prod["lower"])


# ---------------------------------------------------------------------------
# Lexer generation: real ocamllex (.mll). grammar/vimp.yaml only describes
# the language (keywords/punctuation tables, terminal lex patterns); this
# function is where those become ocamllex's own regex/rule idiom -- not
# something the schema should encode itself (its `lex:` fields are plain
# regex-ish strings, not ocamllex character-class syntax).
# ---------------------------------------------------------------------------

def gen_lexer_mll(g: dict) -> str:
    # Keyword rules must precede the generic ident rule: ocamllex resolves
    # an exact-length tie (e.g. input "global" matches both the "global"
    # literal and ident_start ident_char*) by earliest rule, not longest
    # match beyond length -- so without this order every keyword would
    # lex as a plain IDENT instead.
    keyword_rules = "\n".join(f'  | "{word}"' + " " * max(1, 18 - len(word)) + f"{{ {tok} }}" for word, tok in g["keywords"].items())
    punct_rules = "\n".join(f'  | "{op}"' + " " * max(1, 18 - len(op)) + f"{{ {tok} }}" for op, tok in g["punctuation"].items())

    return HEADER + f'''{{
open Vimp_parser

exception Lex_error of {{ line : int; col : int; msg : string }}

let error lexbuf msg =
  let pos = Lexing.lexeme_start_p lexbuf in
  raise (Lex_error {{ line = pos.Lexing.pos_lnum; col = pos.Lexing.pos_cnum - pos.Lexing.pos_bol + 1; msg }})
}}

let digit = ['0'-'9']
let ident_start = ['a'-'z' 'A'-'Z' '_']
let ident_char = ident_start | digit

rule token = parse
  | [' ' '\\t' '\\r']  {{ token lexbuf }}
  | '\\n'              {{ Lexing.new_line lexbuf; token lexbuf }}
  | "//" [^ '\\n']*    {{ token lexbuf }}
{keyword_rules}
{punct_rules}
  | ident_start ident_char* as s  {{ IDENT s }}
  | digit+ as s                   {{ INT (int_of_string s) }}
  | eof                           {{ EOF }}
  | _ as c  {{ error lexbuf (Printf.sprintf "unexpected character %C" c) }}
'''


# ---------------------------------------------------------------------------
# Parser generation
# ---------------------------------------------------------------------------

# Explicit %type declarations: this repo builds Menhir without dune, so
# there's no --infer two-pass typechecking loop; every nonterminal's OCaml
# type must be stated upfront instead.
NONTERMINAL_TYPES = {
    "aexp": "Voblint_CLI.Core.aexp",
    "bexp": "Voblint_CLI.Core.bexp",
    "stmt": "Voblint_CLI.Core.com",
    "stmts": "Voblint_CLI.Core.com",
    "stmts_opt": "Voblint_CLI.Core.com",
    "actuals": "Voblint_CLI.Core.aexp list",
    "formals": "string list",
    "ids": "string list",
    "globals_decl": "string list",
    "globals_opt": "string list",
    "function_decl": "string * string list * Voblint_CLI.Core.com",
    "function_decl_star": "(string * string list * Voblint_CLI.Core.com) list",
}


def type_decls() -> str:
    return "\n".join(f"%type <{t}> {name}" for name, t in NONTERMINAL_TYPES.items())


def token_decls(g: dict) -> str:
    names = list(g["keywords"].values()) + list(g["punctuation"].values()) + ["EOF"]
    lines = ["%token <string> IDENT", "%token <int> INT"]
    lines += [f"%token {n}" for n in names]
    return "\n".join(lines)


def precedence_decls(g: dict) -> str:
    lines = []
    for level in g["precedence"]:
        assoc = {"left": "%left", "right": "%right", "none": "%nonassoc"}[level["assoc"]]
        lines.append(f"{assoc} {' '.join(level['tokens'])}")
    return "\n".join(lines)


def binder(i: int, sym: str) -> str:
    """Menhir binder for rhs position i (symbol name sym), e.g. `v2 = aexp`."""
    return f"v{i} = {sym}"


def rhs_pattern(rhs: list) -> str:
    return " ".join(binder(i, sym) for i, sym in enumerate(rhs))


def render_alt(prod: dict) -> str:
    pattern = rhs_pattern(prod["rhs"])
    is_uminus = prod.get("special") == "unary_minus"
    # Only uminus needs an explicit %prec override: every other rule's own
    # operator token (PLUS/STAR/AND/...) already sits at the end of its rhs,
    # so Menhir's default "rightmost terminal" rule picks the right level
    # automatically. Uminus's only terminal (MINUS) already carries the
    # *binary* Plus/Minus precedence, which would be wrong (too loose) here.
    prec = f" %prec {prod['precedence']}" if is_uminus else ""
    return f"  | {pattern}{prec}\n      {{ {render_action(prod)} }}"


def gen_list_rule(prod: dict) -> str:
    name = prod["name"]
    item = prod.get("list_of") or prod.get("optional_list_of")
    is_optional = "optional_list_of" in prod
    ctor = prod.get("constructor")
    min_count = prod.get("min", 0)

    if is_optional:
        # `stmts_opt`: empty body folds to `empty:`, otherwise defer to the
        # already-generated non-optional list nonterminal (`stmts`).
        base = prod["result"].removesuffix("_opt")
        empty = prod.get("empty", "[]")
        empty_action = f"Voblint_CLI.Core.{empty}" if empty[0].isupper() else empty
        return (
            f"{name}:\n"
            f"  | (* empty *)\n"
            f"      {{ {empty_action} }}\n"
            f"  | cs = {base}\n"
            f"      {{ cs }}"
        )

    if ctor:
        # Left fold via a binary constructor (e.g. Seq), matching the
        # source grammar's own left-recursive `stmts_seq` shape exactly --
        # no separate associativity declaration needed, this is naturally
        # unambiguous LR (SEMI is a concrete token, not an operator needing
        # precedence resolution).
        single = f"  | x = {item}\n      {{ x }}"
        multi = f"  | xs = {name} {prod['separator']} x = {item}\n      {{ Voblint_CLI.Core.{ctor} (xs, x) }}"
        return f"{name}:\n{single}\n{multi}"

    # Plain growing list (actuals/formals/ids).
    alts = []
    if min_count == 0:
        alts.append("  | (* empty *)\n      { [] }")
    alts.append(f"  | x = {item}\n      {{ [x] }}")
    alts.append(f"  | xs = {name} {prod['separator']} x = {item}\n      {{ xs @ [x] }}")
    return f"{name}:\n" + "\n".join(alts)


def gen_program_rule() -> str:
    # Every function parses uniformly via function_decl*; "main" is picked
    # out by string equality in this action, matching both existing parsers
    # (VIMP_Notation.thy's prog_tr, cli/vimp_parser.ml's `program`) -- see
    # grammar/vimp.yaml's header comment on why the record's mandatory
    # prog_main field still makes this a parse-time requirement, not a
    # deferred well-formedness check, under today's imp_prog shape.
    return """program:
  | g = globals_opt fs = function_decl_star EOF
      { let mains, procs = List.partition (fun (n, _, _) -> n = "main") fs in
        let main_body =
          match mains with
          | [ (_, [], b) ] -> b
          | [ (_, _ :: _, _) ] -> failwith "'main' must have no formals"
          | [] -> failwith "missing 'void main() { ... }'"
          | _ -> failwith "more than one 'void main()'"
        in
        Voblint_CLI.Core.make
          (List.map (fun (n, formals, b) -> (n, Voblint_CLI.Core.proc_decl_of formals b)) procs)
          main_body g }

globals_opt:
  | (* empty *)
      { [] }
  | gs = globals_decl
      { gs }

function_decl_star:
  | (* empty *)
      { [] }
  | f = function_decl fs = function_decl_star
      { f :: fs }"""


def gen_named_rule(prod: dict) -> str:
    return f"{prod['name']}:\n  | {rhs_pattern(prod['rhs'])}\n      {{ {render_action(prod)} }}"


def gen_parser(g: dict) -> str:
    productions = g["productions"]
    list_prods, regular_by_result = [], {}
    for p in productions:
        if p.get("list_of") or p.get("optional_list_of"):
            list_prods.append(p)
        elif p.get("special") == "program_structure":
            pass  # hardcoded via gen_program_rule
        elif p["result"] in ("globals", "function"):
            pass  # single-production nonterminals, emitted directly below
        else:
            regular_by_result.setdefault(p["result"], []).append(p)

    rule_blocks = []
    for result, prods in regular_by_result.items():
        alts = "\n".join(render_alt(p) for p in prods)
        rule_blocks.append(f"{result}:\n{alts}")

    for p in list_prods:
        rule_blocks.append(gen_list_rule(p))

    globals_prod = next(p for p in productions if p["name"] == "globals_decl")
    rule_blocks.append(gen_named_rule(globals_prod))
    function_prod = next(p for p in productions if p["name"] == "function_decl")
    rule_blocks.append(gen_named_rule(function_prod))
    rule_blocks.append(gen_program_rule())

    return HEADER + f'''
{token_decls(g)}

{precedence_decls(g)}

{type_decls()}

%start <unit Voblint_CLI.Core.imp_prog_ext> program
%%

{chr(10).join("(* " + b.split(chr(10))[0] + " *)" + chr(10) + b for b in rule_blocks)}
'''


def main():
    grammar_path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_GRAMMAR
    out_dir = Path(sys.argv[2]) if len(sys.argv) > 2 else DEFAULT_OUT
    out_dir.mkdir(parents=True, exist_ok=True)
    g = yaml.safe_load(grammar_path.read_text())
    (out_dir / "vimp_lexer.mll").write_text(gen_lexer_mll(g))
    (out_dir / "vimp_parser.mly").write_text(gen_parser(g))
    print(f"wrote {out_dir / 'vimp_lexer.mll'}")
    print(f"wrote {out_dir / 'vimp_parser.mly'}")


if __name__ == "__main__":
    main()
