#!/usr/bin/env python3
"""Generates the VIMP frontend -- a Menhir parser (vimp_parser.mly) and a
real ocamllex lexer (vimp_lexer.mll) -- from the canonical grammar/vimp.yaml.

This is the source of cli/vimp_parser.mly and cli/vimp_lexer.mll (M5 of the
grammar-unification investigation: the production CLI cutover). The
generated .mly/.mll are committed, the same convention codegen/generated/
already uses for Isabelle-generated sources: `pixi run cli-build`
(scripts/mk/cli-build.sh) needs only menhir/ocamllex/ocamlfind, not Python,
extending its "does not require Isabelle" framing to "does not require
regenerating the frontend either, unless grammar/vimp.yaml changed."

Requires PyYAML to regenerate (`pip install pyyaml`, or `pixi install` from
the repo root already has it) -- not to build.

Usage: python3 scripts/gen_vimp_menhir.py [grammar/vimp.yaml] [out_dir]
"""

import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_GRAMMAR = REPO_ROOT / "grammar" / "vimp.yaml"
DEFAULT_OUT = REPO_ROOT / "cli"

HEADER = (
    "(* GENERATED by scripts/gen_vimp_menhir.py from grammar/vimp.yaml. "
    "Do not hand-edit; regenerate instead. *)\n"
)

# -- `special: name` productions, keyed by that name (not by production
# name -- grammar/vimp.yaml's header comment explains what each covers). ---
SPECIAL_ACTIONS = {
    "integer_literal": "Voblint_CLI.Core.N (Voblint_CLI.Core.Int_of_integer (Z.of_int v0))",
    "unary_minus": """\
match v1 with
      | Voblint_CLI.Core.N (Voblint_CLI.Core.Int_of_integer z) ->
        Voblint_CLI.Core.N (Voblint_CLI.Core.Int_of_integer (Z.neg z))
      | _ ->
        Voblint_CLI.Core.Minus
          (Voblint_CLI.Core.N (Voblint_CLI.Core.Int_of_integer Z.zero), v1)""",
    # Declarations lower to (name, kind option) pairs; the program action
    # keeps the names and collects the annotated kinds (see
    # gen_program_rule).
    "formal_untyped": "(v0, None)",
    "formal_typed": "(v1, Some v0)",
    "globals_untyped": "List.map (fun n -> (n, None)) v1",
    "globals_typed": "List.map (fun n -> (n, Some v1)) v2",
    # A local always carries a kind (no untyped form), so it lowers to a
    # plain (name, kind) pair rather than a `kind option` one.
    "locals_typed": "List.map (fun n -> (n, v0)) v1",
    # A function lowers to (name, formals, locals, body, return kind option).
    # The two productions differ only at rhs position 0 -- the VOID keyword
    # against a `ty` -- so every other position lines up and only the last
    # tuple component changes.
    "function_void": "(v1, v3, v6, v7, None)",
    "function_typed": "(v1, v3, v6, v7, Some v0)",
}


# -- `lower: {ctor: ..., args: [...]}` / `lower: {tuple: [...]}` renderer --

def render_lower_arg(arg: dict) -> str:
    if "rhs" in arg:
        return f"v{arg['rhs']}"
    if "some" in arg:
        return f"(Some {render_lower_arg(arg['some'])})"
    if "none" in arg:
        return "None"
    if "literal" in arg:
        return "true" if arg["literal"] else "false"
    if "int" in arg:
        return f"(Voblint_CLI.Core.Int_of_integer (Z.of_int {arg['int']}))"
    raise ValueError(f"unrecognized lower arg shape: {arg}")


def render_lower(lower: dict) -> str:
    if "tuple" in lower:
        return "(" + ", ".join(f"v{i}" for i in lower["tuple"]) + ")"
    ctor = f"Voblint_CLI.Core.{lower['ctor']}"
    args = [render_lower_arg(a) for a in lower.get("args", [])]
    if not args:
        return ctor
    if len(args) == 1:
        return f"{ctor} {args[0]}"
    return f"{ctor} (" + ", ".join(args) + ")"


def render_action(prod: dict) -> str:
    """Renders exactly one of a production's three possible AST-construction
    shapes -- see grammar/vimp.yaml's header comment for what each covers."""
    special = prod.get("special")
    if special:
        return SPECIAL_ACTIONS[special]
    if "passthrough" in prod:
        return f"v{prod['passthrough']}"
    return render_lower(prod["lower"])


# ---------------------------------------------------------------------------
# Lexer generation: real ocamllex (.mll). grammar/vimp.yaml only describes
# the language (keywords/punctuation tables, terminal lex patterns); this
# function is where those become ocamllex's own regex/rule idiom -- not
# something the schema should encode itself (its `lex:` fields are plain
# regex-ish strings, not ocamllex character-class syntax).
# ---------------------------------------------------------------------------

def gen_lexer_mll(g: dict) -> str:
    # Keyword rules must precede the generic ident rule: ocamllex resolves
    # an exact-length tie (e.g. input "global" matches both the "global"
    # literal and ident_start ident_char*) by earliest rule, not longest
    # match beyond length -- so without this order every keyword would
    # lex as a plain IDENT instead.
    keyword_rules = "\n".join(f'  | "{word}"' + " " * max(1, 18 - len(word)) + f"{{ {tok} }}" for word, tok in g["keywords"].items())
    punct_rules = "\n".join(f'  | "{op}"' + " " * max(1, 18 - len(op)) + f"{{ {tok} }}" for op, tok in g["punctuation"].items())

    return HEADER + f'''{{
open Vimp_parser

exception Lex_error of {{ line : int; col : int; msg : string }}

let error lexbuf msg =
  let pos = Lexing.lexeme_start_p lexbuf in
  raise (Lex_error {{ line = pos.Lexing.pos_lnum; col = pos.Lexing.pos_cnum - pos.Lexing.pos_bol + 1; msg }})
}}

let digit = ['0'-'9']
let ident_start = ['a'-'z' 'A'-'Z' '_']
let ident_char = ident_start | digit

rule token = parse
  | [' ' '\\t' '\\r']  {{ token lexbuf }}
  | '\\n'              {{ Lexing.new_line lexbuf; token lexbuf }}
  | "//" [^ '\\n']*    {{ token lexbuf }}
{keyword_rules}
{punct_rules}
  | ident_start ident_char* as s  {{ IDENT s }}
  | digit+ as s                   {{ INT (int_of_string s) }}
  | eof                           {{ EOF }}
  | _ as c  {{ error lexbuf (Printf.sprintf "unexpected character %C" c) }}
'''


# ---------------------------------------------------------------------------
# Parser generation
# ---------------------------------------------------------------------------

# Explicit %type declarations: this repo builds Menhir without dune, so
# there's no --infer two-pass typechecking loop; every nonterminal's OCaml
# type must be stated upfront instead.
NONTERMINAL_TYPES = {
    "exp": "Voblint_CLI.Core.exp",
    "stmt": "Voblint_CLI.Core.com",
    "stmts": "Voblint_CLI.Core.com",
    "stmts_opt": "Voblint_CLI.Core.com",
    "actuals": "Voblint_CLI.Core.exp list",
    "ty": "Voblint_CLI.Core.ikind",
    "formal": "string * Voblint_CLI.Core.ikind option",
    "formals": "(string * Voblint_CLI.Core.ikind option) list",
    "ids": "string list",
    "globals_decl": "(string * Voblint_CLI.Core.ikind option) list",
    "globals_star": "(string * Voblint_CLI.Core.ikind option) list",
    "local_decl": "(string * Voblint_CLI.Core.ikind) list",
    "locals_star": "(string * Voblint_CLI.Core.ikind) list",
    "function_decl":
        "string * (string * Voblint_CLI.Core.ikind option) list"
        " * (string * Voblint_CLI.Core.ikind) list * Voblint_CLI.Core.com"
        " * Voblint_CLI.Core.ikind option",
    "function_decl_star":
        "(string * (string * Voblint_CLI.Core.ikind option) list"
        " * (string * Voblint_CLI.Core.ikind) list * Voblint_CLI.Core.com"
        " * Voblint_CLI.Core.ikind option) list",
}


def type_decls() -> str:
    return "\n".join(f"%type <{t}> {name}" for name, t in NONTERMINAL_TYPES.items())


def token_decls(g: dict) -> str:
    names = list(g["keywords"].values()) + list(g["punctuation"].values()) + ["EOF"]
    lines = ["%token <string> IDENT", "%token <int> INT"]
    lines += [f"%token {n}" for n in names]
    return "\n".join(lines)


def precedence_decls(g: dict) -> str:
    lines = []
    for level in g["precedence"]:
        assoc = {"left": "%left", "right": "%right", "none": "%nonassoc"}[level["assoc"]]
        lines.append(f"{assoc} {' '.join(level['tokens'])}")
    return "\n".join(lines)


def binder(i: int, sym: str) -> str:
    """Menhir binder for rhs position i (symbol name sym), e.g. `v2 = exp`."""
    return f"v{i} = {sym}"


def rhs_pattern(rhs: list) -> str:
    return " ".join(binder(i, sym) for i, sym in enumerate(rhs))


# Productions whose `com` node owns a Statement index in the compiled CFG --
# exactly the clauses csize charges one for. Seq is absent on purpose: it is
# folded by the stmts list rule and allocates nothing of its own.
def owns_stmt_index(prod: dict) -> bool:
    ctor = (prod.get("lower") or {}).get("ctor")
    return ctor in {
        "SKIP", "Assign", "Check", "If", "While", "Return", "Restore", "Unwind",
        "com.Call", "com.If",
    } or ctor in {"Call"}


def render_alt(prod: dict) -> str:
    pattern = rhs_pattern(prod["rhs"])
    is_uminus = prod.get("special") == "unary_minus"
    # Only uminus needs an explicit %prec override: every other rule's own
    # operator token (PLUS/STAR/AND/...) already sits at the end of its rhs,
    # so Menhir's default "rightmost terminal" rule picks the right level
    # automatically. Uminus's only terminal (MINUS) already carries the
    # *binary* Plus/Minus precedence, which would be wrong (too loose) here.
    prec = f" %prec {prod['precedence']}" if is_uminus else ""
    action = render_action(prod)
    # A command's own source position, recorded where the parser knows it is
    # building a command -- the lexer cannot tell a statement-position IDENT
    # from one inside an expression. Reductions are bottom-up, so these arrive
    # in post-order over the command tree; cli/vimp_frontend.ml pairs them by
    # walking the parsed AST the same way rather than assuming token order.
    if owns_stmt_index(prod):
        action = f"record_stmt_pos $startpos $endpos ({action})"
    return f"  | {pattern}{prec}\n      {{ {action} }}"


def gen_list_rule(prod: dict) -> str:
    name = prod["name"]
    item = prod.get("list_of") or prod.get("optional_list_of")
    is_optional = "optional_list_of" in prod
    ctor = prod.get("constructor")
    min_count = prod.get("min", 0)

    if is_optional:
        # `stmts_opt`: empty body folds to `empty:`, otherwise defer to the
        # already-generated non-optional list nonterminal (`stmts`).
        base = prod["result"].removesuffix("_opt")
        empty = prod.get("empty", "[]")
        empty_action = f"Voblint_CLI.Core.{empty}" if empty[0].isupper() else empty
        return (
            f"{name}:\n"
            f"  | (* empty *)\n"
            f"      {{ {empty_action} }}\n"
            f"  | cs = {base}\n"
            f"      {{ cs }}"
        )

    if ctor:
        # Left fold via a binary constructor (e.g. Seq), matching the
        # source grammar's own left-recursive `stmts_seq` shape exactly --
        # no separate associativity declaration needed, this is naturally
        # unambiguous LR (SEMI is a concrete token, not an operator needing
        # precedence resolution).
        single = f"  | x = {item}\n      {{ x }}"
        multi = f"  | xs = {name} {prod['separator']} x = {item}\n      {{ Voblint_CLI.Core.{ctor} (xs, x) }}"
        return f"{name}:\n{single}\n{multi}"

    # Plain growing list (actuals/formals/ids).
    alts = []
    if min_count == 0:
        alts.append("  | (* empty *)\n      { [] }")
    alts.append(f"  | x = {item}\n      {{ [x] }}")
    alts.append(f"  | xs = {name} {prod['separator']} x = {item}\n      {{ xs @ [x] }}")
    return f"{name}:\n" + "\n".join(alts)


def gen_program_rule() -> str:
    # Every function parses uniformly via function_decl*; "main" is picked
    # out by string equality in this action, matching both existing parsers
    # (VIMP_Notation.thy's prog_tr, cli/vimp_parser.ml's `program`) -- see
    # grammar/vimp.yaml's header comment on why this stays a parse-time
    # diagnostic rather than a deferred well-formedness check.
    return """program:
  | g = globals_star fs = function_decl_star EOF
      { let decl_names = List.map fst g in
        (* Same checks, in the same order, as VIMP_Notation.thy's prog_tr:
           which of several simultaneous collisions is reported first is then
           the same on both frontends too. *)
        check_distinct "procedure" (List.map (fun (n, _, _, _, _) -> n) fs);
        check_distinct "declared global" decl_names;
        List.iter (fun (n, formals, _, _, _) ->
            check_distinct ("formal parameter of " ^ quote n) (List.map fst formals)) fs;
        List.iter (fun (n, formals, _, _, _) ->
            check_no_collision n "global(s) as formal(s)" (List.map fst formals) decl_names) fs;
        List.iter (fun (n, formals, locals, _, _) ->
            let lnames = List.map fst locals in
            check_distinct ("local of " ^ quote n) lnames;
            check_no_collision n "formal(s) as local(s)" lnames (List.map fst formals);
            check_no_collision n "global(s) as local(s)" lnames decl_names) fs;
        check_global_kinds g;
        List.iter (fun (n, formals, _, _, _) -> check_formal_kinds n formals) fs;
        List.iter (fun (n, formals, locals, body, _) ->
            check_declared n
              (decl_names @ List.map fst formals @ List.map fst locals) body) fs;
        let mains, procs = List.partition (fun (n, _, _, _, _) -> n = "main") fs in
        List.iter (fun (n, _, _, body, rk) -> check_void_return n rk body) procs;
        (* main yields no value, so its declaration builds the void form
           whatever kind was written on it. *)
        let main_body =
          match mains with
          | [ (_, [], _, b, _) ] -> b
          | [ (_, _ :: _, _, _, _) ] -> failwith "'main' must have no formals"
          | [] -> failwith "missing 'void main() { ... }'"
          | _ -> failwith "more than one 'void main()'"
        in
        let kind_entries pairs =
          List.filter_map (fun (n, k) ->
              match k with
              | Some k -> Some (Voblint_CLI.Core.TV (n, k))
              | None -> None) pairs
        in
        (* Locals join the flat kind environment, because that environment is
           what compilation resolves a name through. Leaving them out of it is
           what let `uint8 x` in a procedure body be analysed at int32. They
           are additionally recorded per procedure below, which is what the
           scoped declaration table reads. *)
        let kinds =
          kind_entries g
          @ List.concat_map (fun (_, formals, _, _, _) -> kind_entries formals) fs
          @ List.concat_map
              (fun (_, _, locals, _, _) ->
                 List.map (fun (x, k) -> Voblint_CLI.Core.TV (x, k)) locals) fs
        in
        check_kinds_agree
          (List.map (fun (n, k) -> ("the globals", n, k)) (kinded g)
           @ List.concat_map
               (fun (p, formals, locals, _, _) ->
                  List.map (fun (n, k) -> (Printf.sprintf "'%s'" p, n, k)) (kinded formals)
                  @ List.map (fun (n, k) -> (Printf.sprintf "'%s'" p, n, k)) locals)
               fs);
        let scoped_locals =
          List.concat_map (fun (n, _, locals, _, _) ->
              List.map (fun (x, k) -> (n, Voblint_CLI.Core.TV (x, k))) locals) fs
        in
        (* An undeclared return kind stays undeclared: proc_decl_of leaves
           ret_kind None, which the compiler reads as the default kind. Only a
           procedure written with a return kind records one. *)
        let proc_decl formals ret_kind body =
          let xs = List.map fst formals in
          match ret_kind with
          | None -> Voblint_CLI.Core.proc_decl_of xs body
          | Some k -> Voblint_CLI.Core.proc_decl_of_typed xs k body
        in
        Voblint_CLI.Core.mk_program_typed
          (List.map (fun (n, formals, _, b, rk) -> (n, proc_decl formals rk b)) procs)
          main_body (List.map fst g) kinds scoped_locals }

globals_star:
  | (* empty *)
      { [] }
  | l = globals_decl g = globals_star
      { l @ g }

locals_star:
  | (* empty *)
      { [] }
  | l = local_decl ls = locals_star
      { l @ ls }

function_decl_star:
  | (* empty *)
      { [] }
  | f = function_decl fs = function_decl_star
      { f :: fs }"""


def gen_function_rule(prods: list) -> str:
    """All `function`-typed productions form one nonterminal (`function_decl`,
    the name gen_program_rule's function_decl_star references): a procedure
    declared `void` and one declared with a return kind.

    Every alternative closes a definition boundary. Statement indices are
    allocated procedure by procedure with main compiled last, whatever order
    the definitions appear in, so positions have to be grouped by the
    definition they came from rather than left in one flat list. These
    productions reduce at their own closing brace, with the name in scope.
    """
    alts = "\n".join(
        f"  | {rhs_pattern(p['rhs'])}\n      {{ close_definition ({render_action(p)}) }}"
        for p in prods
    )
    return f"function_decl:\n{alts}"


def gen_parser(g: dict) -> str:
    productions = g["productions"]
    list_prods, regular_by_result = [], {}
    for p in productions:
        if p.get("list_of") or p.get("optional_list_of"):
            list_prods.append(p)
        elif p.get("special") == "program_structure":
            pass  # hardcoded via gen_program_rule
        elif p["result"] in ("globals", "local", "function"):
            pass  # single-production nonterminals, emitted directly below
        else:
            regular_by_result.setdefault(p["result"], []).append(p)

    rule_blocks = []
    for result, prods in regular_by_result.items():
        alts = "\n".join(render_alt(p) for p in prods)
        rule_blocks.append(f"{result}:\n{alts}")

    for p in list_prods:
        rule_blocks.append(gen_list_rule(p))

    # All `globals`-typed productions form one nonterminal (`globals_decl`,
    # the name gen_program_rule's globals_star references): a `global`
    # line with or without a kind annotation.
    globals_prods = [p for p in productions if p["result"] == "globals"]
    globals_alts = "\n".join(
        f"  | {rhs_pattern(p['rhs'])}\n      {{ {render_action(p)} }}"
        for p in globals_prods
    )
    rule_blocks.append(f"globals_decl:\n{globals_alts}")
    # `local_decl`, the name gen_program_rule's locals_star references. One
    # alternative only: a local has no untyped form.
    local_prods = [p for p in productions if p["result"] == "local"]
    local_alts = "\n".join(
        f"  | {rhs_pattern(p['rhs'])}\n      {{ {render_action(p)} }}"
        for p in local_prods
    )
    rule_blocks.append(f"local_decl:\n{local_alts}")
    function_prods = [p for p in productions if p["result"] == "function"]
    rule_blocks.append(gen_function_rule(function_prods))
    rule_blocks.append(gen_program_rule())

    return HEADER + f'''
%{{
(* Menhir does not export prelude bindings through the generated .mli, so the
   recorder itself lives in cli/vimp_positions.ml where Vimp_frontend can
   reach it too. See that module for why positions are taken here rather than
   from the token stream, and what order they come out in. *)
let record_stmt_pos = Vimp_positions.record

(* A function_decl's action builds (name, formals, locals, body, return kind);
   closing the bucket here keeps the name and its positions together without a
   second traversal. *)
let close_definition ((name, formals, locals, body, ret_kind) as decl) =
  Vimp_positions.close name;
  ignore formals; ignore locals; ignore body; ignore ret_kind;
  decl

(* Name-collision rules the grammar cannot encode structurally: one name may
   not be introduced twice in the same scope, and a global's cross-call
   persistence, a formal's per-call binding and a local's procedure scope are
   incompatible storage classes for one name. Without them a local shadowing a
   global parses and is then silently ignored -- the name resolves to global
   storage, at the global's kind. VIMP_Notation.thy's prog_tr rejects all of
   these, so raising here keeps both frontends accepting the same programs. *)
let quote n = "\\"" ^ n ^ "\\""

let commas_quote names = String.concat ", " (List.map quote names)

let duplicates names =
  let rec go seen dups = function
    | [] -> List.rev dups
    | n :: rest when List.mem n seen ->
      go seen (if List.mem n dups then dups else n :: dups) rest
    | n :: rest -> go (n :: seen) dups rest
  in
  go [] [] names

let check_distinct kind names =
  match duplicates names with
  | [] -> ()
  | ds -> failwith (Printf.sprintf "duplicate %s: %s" kind (commas_quote ds))

let check_no_collision owner what names against =
  match List.filter (fun n -> List.mem n against) names with
  | [] -> ()
  | bad ->
    failwith (Printf.sprintf "%s declares %s: %s" (quote owner) what (commas_quote bad))

(* Every declaration is explicit. The grammar still admits the unannotated
   forms -- Isabelle mixfix has no epsilon, so optionality is two productions
   and dropping one would change the shared grammar -- so "a formal/global
   without a kind" is rejected here, where the diagnostic can name it, rather
   than silently defaulting the name to the compiler's fallback kind. *)
let unkinded pairs =
  List.filter_map (fun (n, k) -> match k with None -> Some n | Some _ -> None) pairs

let kinded pairs =
  List.filter_map (fun (n, k) -> match k with Some k -> Some (n, k) | None -> None) pairs

let check_formal_kinds owner formals =
  match unkinded formals with
  | [] -> ()
  | bad ->
    failwith
      (Printf.sprintf "%s declares formal parameter(s) without a kind: %s"
         (quote owner) (commas_quote bad))

let check_global_kinds g =
  match unkinded g with
  | [] -> ()
  | bad ->
    failwith
      (Printf.sprintf "global(s) declared without a kind: %s" (commas_quote bad))

(* Compilation resolves a name through one flat kind environment, so a name
   carrying two different kinds anywhere in the program has no representation:
   whichever entry the list happens to hold first would silently win, and the
   other declaration would be analysed at a kind its source never wrote. That
   is a wrong answer rather than an imprecise one, so it is rejected here
   instead. Same name, same kind, in two procedures is fine -- the entries
   agree, and one of them answering for both is exactly right. *)
let string_of_kind (k : Voblint_CLI.Core.ikind) =
  match k with
  | Voblint_CLI.Core.I8 -> "int8"   | Voblint_CLI.Core.U8 -> "uint8"
  | Voblint_CLI.Core.I16 -> "int16" | Voblint_CLI.Core.U16 -> "uint16"
  | Voblint_CLI.Core.I32 -> "int32" | Voblint_CLI.Core.U32 -> "uint32"
  | Voblint_CLI.Core.I64 -> "int64" | Voblint_CLI.Core.U64 -> "uint64"

let check_kinds_agree entries =
  let tbl = Hashtbl.create 32 in
  List.iter
    (fun (owner, name, k) ->
       match Hashtbl.find_opt tbl name with
       | None -> Hashtbl.add tbl name (owner, k)
       | Some (owner', k') when k' <> k ->
         failwith
           (Printf.sprintf
              "'%s' is declared %s in %s and %s in %s; one name may not carry two kinds, because compilation resolves every name through one flat kind environment"
              name (string_of_kind k') owner' (string_of_kind k) owner)
       | Some _ -> ())
    entries

(* A procedure declared `void` yields no value, so `return e` in its body has
   nowhere to deliver e: the caller's Call carries no destination. A bare
   `return` is the void form and stays legal. main is exempt because it is not
   a callable procedure here -- "main may not return" is
   wf_program_compile_input_exec's conjunct, reported by its own path. *)
let rec returns_value (c : Voblint_CLI.Core.com) =
  match c with
  | Voblint_CLI.Core.Return e -> e <> None
  | Voblint_CLI.Core.Seq (a, b) -> returns_value a || returns_value b
  | Voblint_CLI.Core.If (_, a, b) -> returns_value a || returns_value b
  | Voblint_CLI.Core.While (_, a) -> returns_value a
  | Voblint_CLI.Core.SKIP | Voblint_CLI.Core.Assign _ | Voblint_CLI.Core.Check _
  | Voblint_CLI.Core.Call _ | Voblint_CLI.Core.Restore | Voblint_CLI.Core.Unwind ->
    false

let check_void_return owner ret_kind body =
  match ret_kind with
  | Some _ -> ()
  | None ->
    if returns_value body then
      failwith (Printf.sprintf "%s is declared void but returns a value" (quote owner))

(* Every variable a body reads or writes must be a declared global, one of the
   procedure's formals, or one of its declared locals. Classification is per
   occurrence, not per name: a call's callee is a `Call` field, never a `V`, so
   a name that is a procedure at one site and a variable at another is read
   correctly at both. The specials (__voblint_nondet_int, random, min, max)
   are calls too, and so are never seen here. *)
let rec exp_vars acc (e : Voblint_CLI.Core.exp) =
  match e with
  | Voblint_CLI.Core.V x -> x :: acc
  | Voblint_CLI.Core.N _ -> acc
  | Voblint_CLI.Core.Plus (a, b) | Voblint_CLI.Core.Minus (a, b)
  | Voblint_CLI.Core.Times (a, b) | Voblint_CLI.Core.Less (a, b)
  | Voblint_CLI.Core.Eq (a, b) | Voblint_CLI.Core.And (a, b)
  | Voblint_CLI.Core.Or (a, b) -> exp_vars (exp_vars acc a) b
  | Voblint_CLI.Core.Not a -> exp_vars acc a

let rec com_vars acc (c : Voblint_CLI.Core.com) =
  match c with
  | Voblint_CLI.Core.SKIP | Voblint_CLI.Core.Restore | Voblint_CLI.Core.Unwind -> acc
  | Voblint_CLI.Core.Assign (x, e) -> exp_vars (x :: acc) e
  | Voblint_CLI.Core.Check e -> exp_vars acc e
  | Voblint_CLI.Core.Seq (a, b) -> com_vars (com_vars acc a) b
  | Voblint_CLI.Core.If (e, a, b) -> com_vars (com_vars (exp_vars acc e) a) b
  | Voblint_CLI.Core.While (e, a) -> com_vars (exp_vars acc e) a
  | Voblint_CLI.Core.Call (dst, _, args) ->
    List.fold_left exp_vars
      (match dst with Some x -> x :: acc | None -> acc)
      args
  | Voblint_CLI.Core.Return e ->
    (match e with Some e -> exp_vars acc e | None -> acc)

let rec dedup = function
  | [] -> []
  | x :: rest -> x :: dedup (List.filter (fun y -> y <> x) rest)

let check_declared owner in_scope body =
  let used = List.rev (com_vars [] body) in
  match dedup (List.filter (fun x -> not (List.mem x in_scope)) used) with
  | [] -> ()
  | bad ->
    failwith
      (Printf.sprintf "%s uses undeclared variable(s): %s" (quote owner)
         (commas_quote bad))
%}}

{token_decls(g)}

{precedence_decls(g)}

{type_decls()}

%start <unit Voblint_CLI.Core.imp_prog_ext> program
%%

{chr(10).join("(* " + b.split(chr(10))[0] + " *)" + chr(10) + b for b in rule_blocks)}
'''


def main():
    grammar_path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_GRAMMAR
    out_dir = Path(sys.argv[2]) if len(sys.argv) > 2 else DEFAULT_OUT
    out_dir.mkdir(parents=True, exist_ok=True)
    g = yaml.safe_load(grammar_path.read_text())
    (out_dir / "vimp_lexer.mll").write_text(gen_lexer_mll(g))
    (out_dir / "vimp_parser.mly").write_text(gen_parser(g))
    print(f"wrote {out_dir / 'vimp_lexer.mll'}")
    print(f"wrote {out_dir / 'vimp_parser.mly'}")


if __name__ == "__main__":
    main()
