#!/usr/bin/env python3
"""Generates the VIMP source printer (cli/frontend/vimp_printer.ml) from the canonical
manifests/vimp-grammar.yaml, beside the Menhir parser generated from the same file.

The expression printer is read off the grammar: every binary and unary operator
production contributes its token spelling, constructor and precedence level, so
parenthesization follows the one precedence table the parser is built from. A
printed expression therefore parses back to the same tree. Statement and program
layout is not a precedence question and is written out once in the template.

Requires PyYAML to regenerate, not to build.

Usage: python3 scripts/gen_vimp_printer.py [manifests/vimp-grammar.yaml] [out_dir]
"""

import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_GRAMMAR = REPO_ROOT / "manifests" / "vimp-grammar.yaml"
DEFAULT_OUT = REPO_ROOT / "cli" / "frontend"

HEADER = (
    "(* GENERATED by scripts/gen_vimp_printer.py from manifests/vimp-grammar.yaml. "
    "Do not hand-edit; regenerate instead. *)\n"
)

G = "Voblint_CLI.Generated"


def operator_table(grammar: dict) -> tuple[list[tuple], list[tuple]]:
    """Binary and unary operator productions with their spelling and level.

    Levels count from 1 (loosest) in manifest order; atoms print at a level above
    every operator so they never need parentheses.
    """
    punctuation = {token: text for text, token in grammar["punctuation"].items()}
    level_of = {}
    assoc_of = {}
    for index, entry in enumerate(grammar["precedence"], start=1):
        for token in entry["tokens"]:
            level_of[token] = index
            assoc_of[token] = entry["assoc"]

    binary, unary = [], []
    for production in grammar["productions"]:
        if production.get("result") != "exp" or "lower" not in production:
            continue
        rhs = production["rhs"]
        ctor = production["lower"].get("ctor")
        if len(rhs) == 3 and rhs[0] == "exp" and rhs[2] == "exp":
            token = rhs[1]
            binary.append((ctor, punctuation[token], level_of[token], assoc_of[token]))
        elif len(rhs) == 2 and rhs[1] == "exp" and rhs[0] in punctuation:
            token = production.get("precedence", rhs[0])
            unary.append((ctor, punctuation[rhs[0]], level_of[token]))
    return binary, unary


def render(grammar: dict) -> str:
    binary, unary = operator_table(grammar)
    atom_level = len(grammar["precedence"]) + 1
    uminus_level = next(
        index
        for index, entry in enumerate(grammar["precedence"], start=1)
        if "UMINUS" in entry["tokens"]
    )

    binary_cases = []
    for ctor, text, level, assoc in binary:
        left = level if assoc == "left" else level + 1
        right = level if assoc == "right" else level + 1
        binary_cases.append(
            f"  | {G}.{ctor} (a, b) -> paren ctx {level} "
            f'(exp_at {left} a ^ " {text} " ^ exp_at {right} b)'
        )
    unary_cases = [
        f'  | {G}.{ctor} a -> paren ctx {level} ("{text}" ^ exp_at {level} a)'
        for ctor, text, level in unary
    ]

    return (
        HEADER
        + f"""
(* Precedence levels, loosest first, as the grammar's precedence table lists them.
   A subexpression prints in parentheses exactly when its own level is looser than
   the context it sits in. *)

let paren ctx level text = if level < ctx then "(" ^ text ^ ")" else text

let string_of_int_lit n = Z.to_string ({G}.integer_of_int n)

let rec exp_at ctx = function
  | {G}.N n -> paren ctx {atom_level} (string_of_int_lit n)
  | {G}.V x -> x
  (* [0 - e] parses back to itself only when [e] is not a literal: the parser folds
     a negated literal into a negative one, so print that case as a subtraction. *)
  | {G}.Minus ({G}.N z, ({G}.N _ as b)) when Z.equal ({G}.integer_of_int z) Z.zero ->
    paren ctx {binary_level(binary, "Minus")} ("0 - " ^ exp_at {binary_level(binary, "Minus") + 1} b)
  | {G}.Minus ({G}.N z, b) when Z.equal ({G}.integer_of_int z) Z.zero ->
    paren ctx {uminus_level} ("-" ^ exp_at {uminus_level} b)
{chr(10).join(binary_cases)}
{chr(10).join(unary_cases)}

let string_of_exp e = exp_at 0 e

let indent depth = String.make (2 * depth) ' '

(* A sequence prints as its parts in order, and [SKIP] as [skip;] wherever it sits,
   so every command -- including [Seq (SKIP, SKIP)] -- prints to source that parses
   back to itself. The parser builds left-nested sequences, the only shape a
   sequence of statements has. *)
let rec com_lines depth c =
  let pad = indent depth in
  match c with
  | {G}.Seq (a, b) -> com_lines depth a @ com_lines depth b
  | {G}.SKIP -> [pad ^ "skip;"]
  | {G}.Assign (x, e) -> [pad ^ x ^ " = " ^ string_of_exp e ^ ";"]
  | {G}.Return None -> [pad ^ "return;"]
  | {G}.Return (Some e) -> [pad ^ "return " ^ string_of_exp e ^ ";"]
  | {G}.Check (_, e) -> [pad ^ "__voblint_check(" ^ string_of_exp e ^ ");"]
  | {G}.Call (None, f, args) ->
    [pad ^ f ^ "(" ^ String.concat ", " (List.map string_of_exp args) ^ ");"]
  | {G}.Call (Some x, f, args) ->
    [pad ^ x ^ " = " ^ f ^ "(" ^ String.concat ", " (List.map string_of_exp args) ^ ");"]
  | {G}.While (b, body) ->
    [pad ^ "while (" ^ string_of_exp b ^ ") {{"] @ com_lines (depth + 1) body @ [pad ^ "}}"]
  | {G}.If (b, t, e) ->
    [pad ^ "if (" ^ string_of_exp b ^ ") {{"] @ com_lines (depth + 1) t
    @ (match e with
       | {G}.SKIP -> [pad ^ "}}"]
       | _ -> [pad ^ "}} else {{"] @ com_lines (depth + 1) e @ [pad ^ "}}"])
  | _ -> [pad ^ "(* runtime-only command *)"]

let proc_lines (name, formals, body) =
  ["fun " ^ name ^ "(" ^ String.concat ", " formals ^ ") {{"]
  @ com_lines 1 body
  @ ["}}"]

(* [procs] lists every procedure as [(name, formals, body)], [main] among them.
   Blocks -- the globals line, then each procedure -- are separated by one blank line. *)
let program_lines ~globals ~procs =
  let blocks =
    (match globals with [] -> [] | gs -> [["global " ^ String.concat ", " gs ^ ";"]])
    @ List.map proc_lines procs
  in
  List.concat (List.mapi (fun i block -> if i = 0 then block else "" :: block) blocks)

let string_of_program ~globals ~procs =
  String.concat "\\n" (program_lines ~globals ~procs) ^ "\\n"

(* The program type is abstract to OCaml; read it through the exported readers. *)
let string_of_imp_prog p =
  let proc name =
    match {G}.prog_table p name with
    | Some ({G}.Proc_decl_ext (formals, body, ())) -> (name, formals, body)
    | None -> (name, [], {G}.SKIP)
  in
  string_of_program ~globals:({G}.declared_global_vars p)
    ~procs:(("main", [], {G}.prog_main p) :: List.map proc ({G}.prog_procs p))
"""
    )


def binary_level(binary: list[tuple], ctor: str) -> int:
    return next(level for c, _, level, _ in binary if c == ctor)


def main() -> None:
    grammar_path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_GRAMMAR
    out_dir = Path(sys.argv[2]) if len(sys.argv) > 2 else DEFAULT_OUT
    grammar = yaml.safe_load(grammar_path.read_text(encoding="utf-8"))
    (out_dir / "vimp_printer.ml").write_text(render(grammar), encoding="utf-8")


if __name__ == "__main__":
    main()
