#!/usr/bin/env python3
"""Generate a separate print session from ROOTS without reading theory buffers.

The document deliberately starts at HOL: inheriting the capstone heap would
omit its ancestors' theory presentations. Qualified imports preserve each
theory's identity; the generated contents includes only project theories.
"""

import argparse
import json
import re
import shutil
from pathlib import Path

from check_root_entries import COMMENT, entries, owned_theories


REPO = Path(__file__).resolve().parents[1]


def inventory():
    roots = [REPO / line.strip() / "ROOT"
             for line in (REPO / "ROOTS").read_text().splitlines()
             if line.strip() and not line.lstrip().startswith("#")]
    sessions = []
    covered = set()
    names = set()
    for root in roots:
        source = root.read_text()
        headers = re.findall(r'^session\s+"?([\w-]+)"?\s',
                             COMMENT.sub("", source), re.M)
        if len(headers) != 1:
            raise ValueError(f"Expected one session in {root}")
        blocks = list(entries(source))
        dirs = [name for block, name in blocks if block == "directories"]
        owned = owned_theories(root.parent, dirs, roots)
        by_name = {path.stem: path for path in owned}
        if len(by_name) != len(owned):
            raise ValueError(f"Duplicate theory filenames in {root}")
        listed = [name for block, name in blocks if block == "theories"]
        missing = set(listed) - by_name.keys()
        if missing:
            raise ValueError(f"Unresolved theories in {root}: {sorted(missing)}")
        ordered = list(dict.fromkeys(listed + sorted(by_name.keys() - set(listed))))
        theories = []
        for name in ordered:
            if name in names:
                raise ValueError(f"Duplicate LaTeX basename: {name}")
            names.add(name)
            covered.add(by_name[name])
            theories.append({"name": name, "path": str(by_name[name].relative_to(REPO))})
        sessions.append({"name": headers[0], "theories": theories})
    missing = set((REPO / "src").rglob("*.thy")) - covered
    if missing:
        raise ValueError(f"Project theories outside session search paths: {sorted(missing)}")
    return sessions


def presentation(sessions, include_examples=False):
    if include_examples:
        return sessions
    selected = []
    certificate = []
    for session in sessions:
        core = []
        for theory in session["theories"]:
            if not theory["path"].startswith("src/Examples/"):
                core.append(theory)
            elif theory["name"] == "Example_End_To_End_Certificate":
                certificate.append({**session, "theories": [theory], "appendix": True})
        if core:
            selected.append({**session, "theories": core})
    if len(certificate) != 1:
        raise ValueError("Expected exactly one end-to-end certificate appendix")
    return selected + certificate


def generate(destination, include_examples=False):
    sessions = inventory()
    selected = presentation(sessions, include_examples)
    variant = "document-full" if include_examples else "document"
    document = destination / "document"
    document.mkdir(parents=True, exist_ok=True)
    root = [
        '(* Generated by scripts/gen_pdf_session.py; do not edit. *)',
        'session Voblint_Document = HOL +',
        '  options [document = pdf, document_output = "../../output",',
        # Keep/drop directives belong to variants; document_tags assigns tags to commands.
        f'    document_variants = "{variant}=+proof,+ML,+invisible", threads = 12]',
        '  sessions',
        *[f'    "{session["name"]}"' for session in sessions],
        '  theories',
        *[f'    "{session["name"]}.{theory["name"]}"'
          for session in sessions for theory in session["theories"]],
        '  document_files',
        '    "root.tex"',
        '    "contents.tex"',
    ]
    (destination / "ROOT").write_text("\n".join(root) + "\n")
    contents = []
    # Keep all imports above: selection changes presentation, never proof dependencies.
    for session in selected:
        title = session["name"].replace("_", r"\_")
        if session.get("appendix"):
            contents.append(r"\appendix")
            title = "End-to-end certificate"
        contents.append(r"\chapter{" + title + "}")
        for theory in session["theories"]:
            name = theory["name"]
            title = name.replace("_", r"\_")
            contents.extend([r"\clearpage", r"\section{" + title + "}",
                             r"\input{" + name + ".tex}"])
    (document / "contents.tex").write_text("\n".join(contents) + "\n")
    shutil.copyfile(REPO / "document/root.tex", document / "root.tex")
    (destination / "inventory.json").write_text(json.dumps(selected, indent=2) + "\n")
    count = sum(len(session["theories"]) for session in selected)
    print(f"PDF inventory: {count} theories from {len(selected)} project sessions ({variant})")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=REPO / "build/pdf-session")
    parser.add_argument("--include-examples", action="store_true",
                        help="Print all example sessions instead of only the certificate appendix")
    args = parser.parse_args()
    generate(args.output, args.include_examples)
