(* GENERATED by scripts/gen_vimp_menhir.py from manifests/vimp-grammar.yaml. Do not hand-edit; regenerate instead. *)

%{
(* Menhir does not export prelude bindings through the generated .mli, so the
   recorder itself lives in cli/frontend/vimp_positions.ml where Vimp_frontend can
   reach it too. See that module for why positions are taken here rather than
   from the token stream, and what order they come out in. *)
let record_stmt_pos = Vimp_positions.record

(* A function_decl's action builds (name, formals, body); closing the bucket
   here keeps the name, its header and its positions together without a second
   traversal. *)
let close_definition header_start header_end ((name, formals, body) as decl) =
  Vimp_positions.close name header_start header_end;
  ignore formals; ignore body;
  decl
%}

%token <string> IDENT
%token <int> INT
%token GLOBAL
%token FUN
%token SKIP
%token RETURN
%token CHECK
%token IF
%token ELSE
%token WHILE
%token BOOL_TRUE
%token BOOL_FALSE
%token ASSIGN
%token PLUS
%token MINUS
%token STAR
%token SLASH
%token PERCENT
%token LT
%token LE
%token GT
%token GE
%token EQEQ
%token NEQ
%token AND
%token OR
%token NOT
%token LBRACE
%token RBRACE
%token LPAREN
%token RPAREN
%token SEMI
%token COMMA
%token EOF

%left OR
%left AND
%nonassoc EQEQ NEQ
%nonassoc LT LE GT GE
%left PLUS MINUS
%left STAR SLASH PERCENT
%right NOT UMINUS

%type <Voblint_CLI.Generated.exp> exp
%type <Voblint_CLI.Generated.com> stmt
%type <Voblint_CLI.Generated.com> if_stmt
%type <Voblint_CLI.Generated.com> stmts
%type <Voblint_CLI.Generated.com> stmts_opt
%type <Voblint_CLI.Generated.exp list> actuals
%type <string list> formals
%type <string list> ids
%type <string list> globals_decl
%type <string list> globals_opt
%type <string * string list * Voblint_CLI.Generated.com> function_decl
%type <(string * string list * Voblint_CLI.Generated.com) list> function_decl_star

%start <unit Voblint_CLI.Generated.imp_prog_ext> program
%%

(* exp: *)
exp:
  | v0 = IDENT
      { Voblint_CLI.Generated.V v0 }
  | v0 = INT
      { Voblint_CLI.Generated.N (Voblint_CLI.Generated.Int_of_integer (Z.of_int v0)) }
  | v0 = MINUS v1 = exp %prec UMINUS
      { match v1 with
      | Voblint_CLI.Generated.N (Voblint_CLI.Generated.Int_of_integer z) ->
        Voblint_CLI.Generated.N (Voblint_CLI.Generated.Int_of_integer (Z.neg z))
      | _ ->
        Voblint_CLI.Generated.Minus
          (Voblint_CLI.Generated.N (Voblint_CLI.Generated.Int_of_integer Z.zero), v1) }
  | v0 = exp v1 = PLUS v2 = exp
      { Voblint_CLI.Generated.Plus (v0, v2) }
  | v0 = exp v1 = MINUS v2 = exp
      { Voblint_CLI.Generated.Minus (v0, v2) }
  | v0 = exp v1 = STAR v2 = exp
      { Voblint_CLI.Generated.Times (v0, v2) }
  | v0 = exp v1 = SLASH v2 = exp
      { Voblint_CLI.Generated.Div (v0, v2) }
  | v0 = exp v1 = PERCENT v2 = exp
      { Voblint_CLI.Generated.Mod (v0, v2) }
  | v0 = BOOL_TRUE
      { Voblint_CLI.Generated.N (Voblint_CLI.Generated.Int_of_integer (Z.of_int 1)) }
  | v0 = BOOL_FALSE
      { Voblint_CLI.Generated.N (Voblint_CLI.Generated.Int_of_integer (Z.of_int 0)) }
  | v0 = exp v1 = LT v2 = exp
      { Voblint_CLI.Generated.Less (v0, v2) }
  | v0 = exp v1 = LE v2 = exp
      { Voblint_CLI.Generated.LessEq (v0, v2) }
  | v0 = exp v1 = GT v2 = exp
      { Voblint_CLI.Generated.Greater (v0, v2) }
  | v0 = exp v1 = GE v2 = exp
      { Voblint_CLI.Generated.GreaterEq (v0, v2) }
  | v0 = exp v1 = EQEQ v2 = exp
      { Voblint_CLI.Generated.Eq (v0, v2) }
  | v0 = exp v1 = NEQ v2 = exp
      { Voblint_CLI.Generated.NotEq (v0, v2) }
  | v0 = NOT v1 = exp
      { Voblint_CLI.Generated.Not v1 }
  | v0 = exp v1 = AND v2 = exp
      { Voblint_CLI.Generated.And (v0, v2) }
  | v0 = exp v1 = OR v2 = exp
      { Voblint_CLI.Generated.Or (v0, v2) }
  | v0 = LPAREN v1 = exp v2 = RPAREN
      { v1 }
(* stmt: *)
stmt:
  | v0 = SKIP v1 = SEMI
      { record_stmt_pos $startpos $endpos (Voblint_CLI.Generated.SKIP) }
  | v0 = IDENT v1 = ASSIGN v2 = exp v3 = SEMI
      { record_stmt_pos $startpos $endpos (Voblint_CLI.Generated.Assign (v0, v2)) }
  | v0 = RETURN v1 = exp v2 = SEMI
      { record_stmt_pos $startpos $endpos (Voblint_CLI.Generated.Return (Some v1)) }
  | v0 = RETURN v1 = SEMI
      { record_stmt_pos $startpos $endpos (Voblint_CLI.Generated.Return None) }
  | v0 = CHECK v1 = LPAREN v2 = exp v3 = RPAREN v4 = SEMI
      { record_stmt_pos $startpos $endpos (Voblint_CLI.Generated.Check v2) }
  | v0 = if_stmt
      { v0 }
  | v0 = WHILE v1 = LPAREN v2 = exp v3 = RPAREN v4 = LBRACE v5 = stmts_opt v6 = RBRACE
      { record_stmt_pos $startpos $endpos (Voblint_CLI.Generated.While (v2, v5)) }
  | v0 = IDENT v1 = LPAREN v2 = actuals v3 = RPAREN v4 = SEMI
      { record_stmt_pos $startpos $endpos (Voblint_CLI.Generated.Call (None, v0, v2)) }
  | v0 = IDENT v1 = ASSIGN v2 = IDENT v3 = LPAREN v4 = actuals v5 = RPAREN v6 = SEMI
      { record_stmt_pos $startpos $endpos (Voblint_CLI.Generated.Call ((Some v0), v2, v4)) }
(* if_stmt: *)
if_stmt:
  | v0 = IF v1 = LPAREN v2 = exp v3 = RPAREN v4 = LBRACE v5 = stmts_opt v6 = RBRACE v7 = ELSE v8 = LBRACE v9 = stmts_opt v10 = RBRACE
      { record_stmt_pos $startpos $endpos (Voblint_CLI.Generated.If (v2, v5, v9)) }
  | v0 = IF v1 = LPAREN v2 = exp v3 = RPAREN v4 = LBRACE v5 = stmts_opt v6 = RBRACE
      { record_stmt_pos $startpos $endpos (Voblint_CLI.Generated.If (v2, v5, (record_stmt_pos $endpos $endpos (Voblint_CLI.Generated.SKIP)))) }
  | v0 = IF v1 = LPAREN v2 = exp v3 = RPAREN v4 = LBRACE v5 = stmts_opt v6 = RBRACE v7 = ELSE v8 = if_stmt
      { record_stmt_pos $startpos $endpos (Voblint_CLI.Generated.If (v2, v5, v8)) }
(* stmts: *)
stmts:
  | x = stmt
      { x }
  | xs = stmts  x = stmt
      { Voblint_CLI.Generated.Seq (xs, x) }
(* stmts_opt: *)
stmts_opt:
  | (* empty *)
      { record_stmt_pos $startpos $endpos (Voblint_CLI.Generated.SKIP) }
  | cs = stmts
      { cs }
(* actuals: *)
actuals:
  | (* empty *)
      { [] }
  | x = exp
      { [x] }
  | xs = actuals COMMA x = exp
      { xs @ [x] }
(* formals: *)
formals:
  | (* empty *)
      { [] }
  | x = IDENT
      { [x] }
  | xs = formals COMMA x = IDENT
      { xs @ [x] }
(* ids: *)
ids:
  | x = IDENT
      { [x] }
  | xs = ids COMMA x = IDENT
      { xs @ [x] }
(* globals_decl: *)
globals_decl:
  | v0 = GLOBAL v1 = ids v2 = SEMI
      { v1 }
(* function_decl: *)
function_decl:
  | v0 = FUN v1 = IDENT v2 = LPAREN v3 = formals v4 = RPAREN v5 = LBRACE v6 = stmts_opt v7 = RBRACE
      { close_definition $startpos $endpos(v4) ((v1, v3, v6)) }
(* program: *)
program:
  | g = globals_opt fs = function_decl_star EOF
      { let mains, procs = List.partition (fun (n, _, _) -> n = "main") fs in
        let main_body =
          match mains with
          | [ (_, [], b) ] -> b
          | [ (_, _ :: _, _) ] -> failwith "'main' must have no formals"
          | [] -> failwith "missing 'fun main() { ... }'"
          | _ -> failwith "more than one 'fun main()'"
        in
        Voblint_CLI.Generated.mk_program
          (List.map (fun (n, formals, b) -> (n, Voblint_CLI.Generated.Proc_decl_ext (formals, b, ()))) procs)
          main_body g }

globals_opt:
  | (* empty *)
      { [] }
  | gs = globals_decl
      { gs }

function_decl_star:
  | (* empty *)
      { [] }
  | f = function_decl fs = function_decl_star
      { f :: fs }
