theory CFG_Collect_Activation
  imports CFG_Collect_Trace
begin

section \<open>Activation-indexed collecting semantics (call-only context)\<close>

text \<open>
  A parallel, activation-aware refinement of the concrete trace collecting
  \<^const>\<open>trace_witness\<close>.  It threads a call context \<open>'c\<close> alongside the SAME concrete
  trace, following Goblint's protocol: context is selected at a call from the callee
  entry state and is otherwise unchanged (Goblint \<open>Spec.context\<close> is call-only, never
  updated on ordinary CFG edges).  Concretely:

    \<^item> ordinary (non-\<^const>\<open>EA_Enter\<close>) edges keep the context (\<open>intra\<close>);
    \<^item> an \<^const>\<open>EA_Enter\<close> edge switches to the routed callee context
      \<open>enterc c (last tau)\<close> --- Goblint's \<open>context f (enter ...)\<close> (\<open>enter\<close>);
    \<^item> a combine restores the caller context \<open>combc c1 c2\<close> from the caller's own
      threaded context \<open>c1\<close> --- Goblint's \<open>combine_env\<close> / \<open>combine_assign\<close> (\<open>combine\<close>).

  The witness is domain-independent: the routing \<open>enterc\<close>, the return context map
  \<open>combc\<close>, and the start context \<open>seedc\<close> are parameters.  It forgets to
  \<^const>\<open>trace_witness\<close> (\<open>trace_witness_act_imp_trace_witness\<close>), so its last-store
  projection is a genuine subset of the reachable states --- the concrete semantics is
  the ground truth and is left unchanged.
\<close>

subsection \<open>The activation witness\<close>

inductive trace_witness_act ::
  "('c \<Rightarrow> store \<Rightarrow> 'c) \<Rightarrow> ('c \<Rightarrow> 'c \<Rightarrow> 'c) \<Rightarrow> 'c
   \<Rightarrow> cfg \<Rightarrow> store set \<Rightarrow> pp \<Rightarrow> 'c \<Rightarrow> trace \<Rightarrow> bool"
  for enterc :: "'c \<Rightarrow> store \<Rightarrow> 'c"
  and combc :: "'c \<Rightarrow> 'c \<Rightarrow> 'c"
  and seedc :: 'c
  and g :: cfg and S :: "store set"
where
  entry: "v = cfg_entry g \<Longrightarrow> s \<in> S
      \<Longrightarrow> trace_witness_act enterc combc seedc g S v seedc [s]"
| proc_entry:
    "(cfg_entry g, EA_Enter xs es, v) \<in> edges g \<Longrightarrow>
     s \<in> edge_collect (EA_Enter xs es) S \<Longrightarrow>
     trace_witness_act enterc combc seedc g S v seedc [s]"
| intra: "(u, a, v) \<in> edges g \<Longrightarrow> \<not> is_enter_action a
      \<Longrightarrow> trace_witness_act enterc combc seedc g S u c tr
      \<Longrightarrow> edge_step a (last tr) = Some s'
      \<Longrightarrow> trace_witness_act enterc combc seedc g S v c (tr @ [s'])"
| enter: "(u, EA_Enter xs es, v) \<in> edges g
      \<Longrightarrow> trace_witness_act enterc combc seedc g S u c tau
      \<Longrightarrow> edge_step (EA_Enter xs es) (last tau) = Some s'
      \<Longrightarrow> trace_witness_act enterc combc seedc g S v
            (enterc c (last tau)) (tau @ [s'])"
| combine: "(cl, ex, v, dst, rex) \<in> combines g
      \<Longrightarrow> trace_witness_act enterc combc seedc g S cl c1 tau
      \<Longrightarrow> trace_witness_act enterc combc seedc g S ex c2 rho
      \<Longrightarrow> r \<in> combine_collect dst rex (last tau) (last rho)
      \<Longrightarrow> trace_witness_act enterc combc seedc g S v
            (combc c1 c2) (tau @ tl rho @ [r])"

text \<open>Full case elimination (the induction rule \<open>trace_witness_act.induct\<close> and the
  introduction rules \<open>trace_witness_act.intros\<close> are generated by the package).\<close>
inductive_cases trace_witness_actE:
  "trace_witness_act enterc combc seedc g S v c tr"

subsection \<open>Context discipline: constant on edges, routed at enter, resumed at combine\<close>

text \<open>Task 3 --- an ordinary (non-\<^const>\<open>EA_Enter\<close>) edge keeps the context \<open>c\<close>.\<close>
lemma act_step_preserves_ctx:
  assumes "(u, a, v) \<in> edges g" and "\<not> is_enter_action a"
    and "trace_witness_act enterc combc seedc g S u c tr"
    and "edge_step a (last tr) = Some s'"
  shows "trace_witness_act enterc combc seedc g S v c (tr @ [s'])"
  by (rule trace_witness_act.intra[OF assms])

text \<open>Task 4 --- a callee entry sits at the routed callee context \<open>enterc c (last tau)\<close>.\<close>
lemma act_enter_routes_ctx:
  assumes "(u, EA_Enter xs es, v) \<in> edges g"
    and "trace_witness_act enterc combc seedc g S u c tau"
    and "edge_step (EA_Enter xs es) (last tau) = Some s'"
  shows "trace_witness_act enterc combc seedc g S v
           (enterc c (last tau)) (tau @ [s'])"
  by (rule trace_witness_act.enter[OF assms])

text \<open>Task 5 --- combine resumes the caller context via \<open>combc c1 c2\<close>, where \<open>c2\<close>
  is the callee context threaded through the activation witness.\<close>
lemma act_combine_ctx:
  assumes "(cl, ex, v, dst, rex) \<in> combines g"
    and "trace_witness_act enterc combc seedc g S cl c1 tau"
    and "trace_witness_act enterc combc seedc g S ex c2 rho"
    and "r \<in> combine_collect dst rex (last tau) (last rho)"
  shows "trace_witness_act enterc combc seedc g S v
           (combc c1 c2) (tau @ tl rho @ [r])"
  by (rule trace_witness_act.combine[OF assms])

text \<open>With a caller-projecting return map the resumed context IS the caller context.\<close>
lemma act_combine_resumes_caller:
  assumes "(cl, ex, v, dst, rex) \<in> combines g"
    and "trace_witness_act enterc (\<lambda>c1 c2. c1) seedc g S cl c1 tau"
    and "trace_witness_act enterc (\<lambda>c1 c2. c1) seedc g S ex c2 rho"
    and "r \<in> combine_collect dst rex (last tau) (last rho)"
  shows "trace_witness_act enterc (\<lambda>c1 c2. c1) seedc g S v
           c1 (tau @ tl rho @ [r])"
  using trace_witness_act.combine[OF assms] by simp

subsection \<open>Forgetful collapse to the concrete semantics\<close>

text \<open>Task 2 --- every activation witness forgets to the concrete \<^const>\<open>trace_witness\<close>.\<close>
theorem trace_witness_act_imp_trace_witness:
  "trace_witness_act enterc combc seedc g S v c tr \<Longrightarrow> trace_witness g S v tr"
proof (induction rule: trace_witness_act.induct)
  case (entry v s)
  then show ?case by (rule trace_witness.entry)
next
  case (proc_entry xs es v s)
  then show ?case by (rule trace_witness.proc_entry)
next
  case (intra u a v c tr s')
  then show ?case by (auto intro: trace_witness.edge)
next
  case (enter u xs es v c tau s')
  then show ?case by (auto intro: trace_witness.edge)
next
  case (combine cl ex v dst rex c1 tau c2 rho r)
  then show ?case by (auto intro: trace_witness.combine)
qed

definition cfg_collect_trace_act ::
  "('c \<Rightarrow> store \<Rightarrow> 'c) \<Rightarrow> ('c \<Rightarrow> 'c \<Rightarrow> 'c) \<Rightarrow> 'c
   \<Rightarrow> cfg \<Rightarrow> store set \<Rightarrow> pp \<Rightarrow> 'c \<Rightarrow> trace set" where
  "cfg_collect_trace_act enterc combc seedc g S v ctx =
     {tr. trace_witness_act enterc combc seedc g S v ctx tr}"

definition cfg_collect_ctx_act ::
  "('c \<Rightarrow> store \<Rightarrow> 'c) \<Rightarrow> ('c \<Rightarrow> 'c \<Rightarrow> 'c) \<Rightarrow> 'c
   \<Rightarrow> cfg \<Rightarrow> store set \<Rightarrow> pp \<Rightarrow> 'c \<Rightarrow> store set" where
  "cfg_collect_ctx_act enterc combc seedc g S v ctx =
     {last tr | tr. trace_witness_act enterc combc seedc g S v ctx tr}"

text \<open>The activation collecting is a genuine subset of the reachable stores: the
  context index only refines which concrete stores it names, never adds any.\<close>
theorem cfg_collect_ctx_act_le_collect:
  "cfg_collect_ctx_act enterc combc seedc g S v ctx \<subseteq> cfg_collect g S v"
  unfolding cfg_collect_ctx_act_def
  by (auto dest: trace_witness_act_imp_trace_witness trace_witness_last_in_cfg_collect)

subsection \<open>A small recursive example: the context switch\<close>

text \<open>
  Context = call depth (\<^typ>\<open>nat\<close>), routed by \<open>enterc c _ = Suc c\<close> (a domain-independent
  witness that each call opens a fresh context) and resumed by the caller projection
  \<open>combc c1 _ = c1\<close>.  A self-entering procedure (edge \<open>(p, EA_Enter [] [], p)\<close>) recursively
  re-enters, and the context deepens \<open>0 \<rightarrow> 1 \<rightarrow> 2\<close> --- one switch per activation.
\<close>

lemma act_recursion_switches_context:
  fixes g :: cfg and s0 :: store and p :: pp
  assumes s0: "s0 \<in> S"
    and e1: "(cfg_entry g, EA_Enter [] [], p) \<in> edges g"
    and e2: "(p, EA_Enter [] [], p) \<in> edges g"
  shows "trace_witness_act (\<lambda>c s. Suc c) (\<lambda>c1 c2. c1) (0::nat) g S p
           (Suc (Suc 0)) [s0, enter_state s0, enter_state (enter_state s0)]"
proof -
  have w0: "trace_witness_act (\<lambda>c s. Suc c) (\<lambda>c1 c2. c1) 0 g S (cfg_entry g) 0 [s0]"
    by (rule trace_witness_act.entry[OF refl s0])
  have st1: "edge_step (EA_Enter [] []) (last [s0]) = Some (enter_state s0)"
    by (simp add: bind_formals_def)
  have w1: "trace_witness_act (\<lambda>c s. Suc c) (\<lambda>c1 c2. c1) 0 g S p (Suc 0) [s0, enter_state s0]"
    using trace_witness_act.enter[OF e1 w0 st1] by simp
  have st2: "edge_step (EA_Enter [] []) (last [s0, enter_state s0]) = Some (enter_state (enter_state s0))"
    by (simp add: bind_formals_def)
  show "trace_witness_act (\<lambda>c s. Suc c) (\<lambda>c1 c2. c1) 0 g S p
          (Suc (Suc 0)) [s0, enter_state s0, enter_state (enter_state s0)]"
    using trace_witness_act.enter[OF e2 w1 st2] by simp
qed

text \<open>An ordinary edge out of the depth-2 activation keeps the context at \<open>Suc (Suc 0)\<close>.\<close>
lemma act_recursion_intra_keeps_context:
  fixes g :: cfg and s0 :: store and p q :: pp
  assumes w2: "trace_witness_act (\<lambda>c s. Suc c) (\<lambda>c1 c2. c1) (0::nat) g S p
                 (Suc (Suc 0)) [s0, enter_state s0, enter_state (enter_state s0)]"
    and e3: "(p, EA_Nop, q) \<in> edges g"
  shows "trace_witness_act (\<lambda>c s. Suc c) (\<lambda>c1 c2. c1) (0::nat) g S q
           (Suc (Suc 0))
           [s0, enter_state s0, enter_state (enter_state s0), enter_state (enter_state s0)]"
proof -
  have ne: "\<not> is_enter_action EA_Nop" by (simp add: is_enter_action_def)
  have st: "edge_step EA_Nop (last [s0, enter_state s0, enter_state (enter_state s0)])
              = Some (enter_state (enter_state s0))" by simp
  show ?thesis using trace_witness_act.intra[OF e3 ne w2 st] by simp
qed

end
